# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleAppForVonageSDk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleAppForVonageSDk
    pod 'VonageClientSDKVoice', '1.6.0'
#pod 'NexmoClient', '4.3.2' // working
  target 'ExampleAppForVonageSDkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleAppForVonageSDkUITests' do
    # Pods for testing
  end

end
